services:
  # Traefik reverse proxy - Local configuration
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    command:
      # Enable dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Allow insecure access for local testing
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=mlops-network"
      # Single HTTP entrypoint for local testing
      - "--entrypoints.web.address=:80"
      # Logging
      - "--log.level=DEBUG"
      - "--accesslog=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      # Traefik dashboard accessible at http://localhost:8080
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana:/etc/grafana/provisioning/dashboards:ro
      - ./configs/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
      - ./configs/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./configs/grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml:ro
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_SERVER_ROOT_URL: http://grafana.localhost
    env_file:
      - .env
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      sh -c "
        mkdir -p /mlflow/artifacts &&
        chmod -R 777 /mlflow &&
        mlflow server --host=0.0.0.0 --port=5000 --backend-store-uri=sqlite:///mlflow/mlflow.db --default-artifact-root=/mlflow/artifacts --serve-artifacts
      "
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow-data:/mlflow
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; print(urllib.request.urlopen('http://localhost:5000/health').read().decode())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow.rule=Host(`mlflow.localhost`)"
      - "traefik.http.routers.mlflow.entrypoints=web"
      - "traefik.http.services.mlflow.loadbalancer.server.port=5000"

  # Prefect orchestration server
  prefect:
    image: prefecthq/prefect:3-latest
    command: >
      sh -c "
        prefect server start --host 0.0.0.0 --port 4200
      "
    environment:
      # This is the public-facing URL for the API, used by the UI in your browser.
      # Traefik routes requests from prefect.localhost to this service.
      - PREFECT_UI_API_URL=http://prefect.localhost/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
      - PREFECT_HOME=/opt/prefect
    volumes:
      - prefect-data:/opt/prefect
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; print(urllib.request.urlopen('http://localhost:4200/health').read().decode())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prefect.rule=Host(`prefect.localhost`)"
      - "traefik.http.routers.prefect.entrypoints=web"
      - "traefik.http.services.prefect.loadbalancer.server.port=4200"

  # FastAPI application
  api:
    image: ghcr.io/kingabzpro/a-to-z-mlops:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
      MODEL_NAME: ${MODEL_NAME}
      MODEL_VERSION: ${MODEL_VERSION:-1}
      CACHE_TTL: ${CACHE_TTL:-3600}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_API_KEY: ${KAGGLE_API_KEY}
      # FIX: Use internal Docker network URLs for service-to-service communication
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_SERVER_API_URL: http://prefect:4200/api
      RUN_PIPELINE: true
    env_file:
      - .env
    depends_on:
      - mlflow
      - prefect
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs:ro
      - mlflow-data:/mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:7860/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=7860"

  # Load testing with Locust
  locust:
    image: locustio/locust:latest
    volumes:
      - ./tests/stress_test.py:/home/locust/locustfile.py:ro
      - ./.env:/home/locust/.env:ro
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        pip install python-dotenv
        exec locust -f /home/locust/locustfile.py --host=http://api:7860
    environment:
      API_KEY: ${API_KEY}
      TARGET_HOST: http://api:7860
      LOCUST_MODE: ${LOCUST_MODE:-standalone}
      LOCUST_USERS: ${LOCUST_USERS:-100}
      LOCUST_SPAWN_RATE: ${LOCUST_SPAWN_RATE:-10}
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - mlops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.locust.rule=Host(`locust.localhost`)"
      - "traefik.http.routers.locust.entrypoints=web"
      - "traefik.http.services.locust.loadbalancer.server.port=8089"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mlflow-data:
    driver: local
  prefect-data:
    driver: local

networks:
  mlops-network:
    driver: bridge
